# Generated by Django 3.2.7 on 2021-09-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_comment',
            name='comment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.comment'),
        ),
    ]
