# Generated by Django 3.2.7 on 2021-09-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mailbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbox',
            old_name='mailbox',
            new_name='email',
        ),
    ]
